[Appearance]\ncustom_palette=true\ncolor_scheme_path=/home/balaji/.local/share/color-schemes/DankMatugen.colors\n
icon_theme=Colloid-Purple-Catppuccin
color_scheme_path=/home/balaji/.local/share/color-schemes/DankMatugen.colors
custom_palette=true
